### PR TITLE
Revert "fs_mgr_fstab: removing fs_mgr_get_entry_for_mount_point_after()"

### PR DESCRIPTION
**Pull request by TeamFahQ**
Fixes build error with bootable/recovery/roots.cpp line 132:
` rec = fs_mgr_get_entry_for_mount_point_after(rec, fstab, path);`
Sorry, I forgot to save the error before I tested the fix and made this pull request.
Forgive me for not pushing this to gerrit, but since the commit has already been made in LineageOs, I didn't see it fit to do so.

### CODE REVIEW

**Comment by ItzLevvie** [comment]
@TeamFahQ Close?

Please submit patches through LineageOS Gerrit

**Comment by xdevs23** [comment]
there's no point in leaving this open

**Comment by ItzLevvie** [comment]
Hey there, @TeamFahQ!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by ItzLevvie** [comment]
Hey there, @TeamFahQ!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by ItzLevvie** [comment]
Hey there, @TeamFahQ!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by haggertk** [comment]
Code changes to LineageOS are submitted through Gerrit - https://wiki.lineageos.org/how-to/submitting-patches

**Pull request closed without merging**
